language: cpp

compiler:
  - gcc
  - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - time

script:
  - make clean
  - make
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-100.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-200.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-500.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-1000.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-5000.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-10000.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-50000.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-100000.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-500000.fa testd.maf
  - /usr/bin/time -v ./bin/bioinformatics d test/data/test-1000000.fa testd.maf
